name: Goose_extension
on:
   issues:
      types: ['opened','edited']

permissions:
   contents: write
   pull-requests: write
   issues: write

env:
   GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
   ISSUE_NUMBER: ${{ github.event.issue.number }}
   PR_NUMBER: ${{ github.event.pull_request.number }}
   GH_TOKEN: ${{ github.token }}
   REPOSITORY: ${{ github.repository }}

jobs:
   goose-comment:
      runs-on: self-hosted
      steps:
            - name: Check out repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0


            - name: Create instructions for Goose
              run: |
                  cat <<EOF > instructions.txt
                  Apply label "bug" if body of issue $ISSUE_NUMBER in repository $REPOSITORY contains word "error" else Apply label "enhancement" if body of issue $ISSUE_NUMBER in repository $REPOSITORY contains word "test"
                  EOF

            - name: Test
              run: cat instructions.txt

            - name: Run Goose with github extension
              run: |
                  . ./.bashrc
                  cd /home/suresh/goose
                  goose run --with-extension "GITHUB_PERSONAL_ACCESS_TOKEN=${{ secrets.PAT }} npx -y @modelcontextprotocol/server-github" --instructions instructions.txt
