name: Goose_extension
on:
   issues:
      types: ['opened','edited']

permissions:
   contents: write
   pull-requests: write
   issues: write

env:
   ISSUE_NUMBER: ${{ github.event.issue.number }}
   PR_NUMBER: ${{ github.event.pull_request.number }}
   GH_TOKEN: ${{ github.token }}
   REPOSITORY: ${{ github.repository }}

jobs:
   goose-comment:
      runs-on: self-hosted
      steps:
            - name: Check out repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0


            - name: Create instructions for Goose
              run: |
                  cat <<EOF > instructions.txt
                  Analyze the issue $ISSUE_NUMBER in repository $REPOSITORY and apply appropriate labels based on the following rules:
                   1. Apply label "bug" if the issue description or title contains words like "error", "crash", "broken", "not working", "fails"
                   2. Apply label "enhancement" if the issue description or title contains words like "improve", "better", "optimize", "enhance"
                   3. Apply label "feature-request" if the issue description or title contains words like "add", "new", "implement", "would like"
                   4. Apply label "documentation" if the issue description or title contains words like "docs", "readme", "documentation", "guide"
                   5. Apply label "question" if the issue description or title contains words like "how", "what", "why", "help", "?"
                   6. Apply label "duplicate" if the issue description or title contains words like "same as", "duplicate of", "already reported"
                   7. Apply label "help-wanted" if the issue description or title contains words like "help needed", "looking for help", "contributions welcome"
                   8. Apply label "good-first-issue" if the issue description or title contains words like "beginner", "starter", "easy", "simple"
                   9. Apply label "priority-high" if the issue description or title contains words like "urgent", "critical", "blocking", "important"
                   10. Apply label "priority-low" if the issue description or title contains words like "nice to have", "minor", "low priority"
                  EOF

            - name: Test
              run: cat instructions.txt

            - name: Run Goose with github extension
              run: |
                  . ~/.bashrc
                  goose run --with-extension "GITHUB_PERSONAL_ACCESS_TOKEN=${{ secrets.PAT }} npx -y @modelcontextprotocol/server-github" --instructions instructions.txt
